### ISSUE TITLE
Error on Setup

### ISSUE THREAD

**Issue by goofy79** [Schnitzel/hass-miner#168]
Hello, 

i have the HA Version 2023.06.01 and the BraiinOS+ 2022-04-29-0-5eb2c5fe-22.02.4-plus on my S9.
If i try to setup the miner on the HA i get the message "error on setup".
Is there something wrong ?  The Integration have the Version 0.6.0

BR

**Comment by UpstreamData** [comment]
This is an issue with a function used to setup the miner in newer version of HASS, the name of the function changed.  This should be the same issue as #166, getting fixed in #39.
