### ISSUE TITLE
error while add miner

### ISSUE THREAD

**Issue by hyperion11** [Schnitzel/hass-miner#169]
Error while add miner

Home Assistant 2023.6.1
Supervisor 2023.06.2
Operating System 10.2

Logger: custom_components.miner.config_flow
Source: custom_components/miner/config_flow.py:36
Integration: Miner ([documentation](https://github.com/Schnitzel/hass-miner), [issues](https://github.com/Schnitzel/hass-miner/issues))
First occurred: 08:00:29 (6 occurrences)
Last logged: 08:06:17

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/miner/config_flow.py", line 36, in validate_input
    miner = await miner_factory.get_miner(miner_ip)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miners/miner_factory.py", line 96, in get_miner
    new_model, new_api = await asyncio.wait_for(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miners/miner_factory.py", line 271, in _get_miner_type
    model = version["VERSION"][0]["Type"]
            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'Type'

**Comment by hyperion11** [comment]
This solution not help
https://github.com/Schnitzel/hass-miner/issues/166

**Comment by UpstreamData** [comment]
That should be fixed when we merge #39, it's an issue with a very old version of pyasic.

**Comment by eek-nz** [comment]
I have the identical first line issue and #166 was also not helpful. Is #39 merged yet? I'm too much of a noob to know.
My second line error is a little differnet:
  File "/usr/local/lib/python3.11/site-packages/miners/miner_factory.py", line 154, in get_miner
    if "BOSMiner" in api:
I am connecting to a BOS S19.
I've only had HASS-Miner installed for 2 days so it should be current. There are no updates outstanding on the HASS install.
Should I open it as a diffenet issue? I'm hopeful #39 isn't merged yet and it will resolve when it is. 
No thread hijack intended but it appears to be the same issue.

**Comment by UpstreamData** [comment]
If you're on the [pre-release beta version](https://github.com/Schnitzel/hass-miner/releases/tag/v1.0.0-beta1), then yes, this is a bug.  It'll be related to `pyasic` though it seems, likely not `hass-miner` itself.  You can provide the whole trace back here and I'll see if I can solve it, or you can open a new issue for [`pyasic`](github.com/UpstreamData/pyasic) and I'll solve it there.

**Comment by eek-nz** [comment]
Sorry to be hopeless - How would I get a trace back? What I have I got from the logs, but it's only showing those couple of lines. I have that downloaded in a file. I reckon you're looking for something more pyasic specific.

**Comment by UpstreamData** [comment]
Send whatever you can from that log, usually if you click the error log and click load full logs it will give you a full trackback.

**Comment by eek-nz** [comment]
Now I'm feeling bad about being both blind and thread hijacking. I see Traceback is right there in the logs. I just did a fresh one and the log output is:
Traceback (most recent call last):
  File "/config/custom_components/miner/config_flow.py", line 36, in validate_input
    miner = await miner_factory.get_miner(miner_ip)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miners/miner_factory.py", line 154, in get_miner
    if "BOSMiner" in api:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

The miner is running BOS+ from SSD. I'm in NZ so my time zone is probably inconvenient.

**Comment by UpstreamData** [comment]
No problem, we care more about getting problems fixed anyway, it's all still a beta so it's not super pertinent that everything be organized perfectly.

A little strange that error is coming up though, the package version for `pyasic` might need an update, as like 154 isn't inside the `get_miner` function, it's actually part of a mapping of miner types.

@Schnitzel latest version of `pyasic` is 0.37.6, can we pin to that for now?

**Comment by UpstreamData** [comment]
Something is really outdated with your version of `pyasic` it seems now looking at it more closely.  Maybe give uninstalling and reinstalling the whole HACS package a shot and see if that helps?

**Comment by eek-nz** [comment]
Sure. I've had HACS on a long time. Pretty sure there was an update I did last week. But I can give it a try. The only other thing in HACS is my Sonoff. I'm not using any of the Sonoff things in winter so it can break.

**Comment by eek-nz** [comment]
Took a minute to get HACS off. Got it off, checked I'm compliant to all reqs. Authorized it at Github, added the repo and installed. Ran through it all again. Error looks the same:

Logger: custom_components.miner.config_flow
Source: custom_components/miner/config_flow.py:36
Integration: Miner ([documentation](https://github.com/Schnitzel/hass-miner), [issues](https://github.com/Schnitzel/hass-miner/issues))
First occurred: 3:33:13 PM (1 occurrences)
Last logged: 3:33:13 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/miner/config_flow.py", line 36, in validate_input
    miner = await miner_factory.get_miner(miner_ip)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miners/miner_factory.py", line 154, in get_miner
    if "BOSMiner" in api:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

Did a restart and checked again just to be sure. Same error.

**Comment by UpstreamData** [comment]
Hmm.  Maybe just have to wait until the pinned version gets updated then.  I can't remember how HACS does dependency management or if it's possible to update it, but you could edit the manifest.json file for now to pin the right version if you want.  Should be in custom components in your HASS root, you'd have to do it via SSH.

**Comment by DannyAmdax** [comment]
> If you're on the [pre-release beta version](https://github.com/Schnitzel/hass-miner/releases/tag/v1.0.0-beta1), then yes, this is a bug. It'll be related to `pyasic` though it seems, likely not `hass-miner` itself. You can provide the whole trace back here and I'll see if I can solve it, or you can open a new issue for [`pyasic`](github.com/UpstreamData/pyasic) and I'll solve it there.

Great! Wasn't able to connect the miners with the stable release. Pre-release works for me 👍🏻

**Comment by Schnitzel** [comment]
This has been addressed in `v1.0.1`.
