### ISSUE TITLE
Set miner username and password

### ISSUE THREAD

**Issue by UpstreamData** [Schnitzel/hass-miner#171]
A user should be able to set the username/password for the miner via the HASS interface.  This could be passed as an initial configuration parameter to the config flow.  It would also be nice to be able to change it after the miner is created via the UI, and just have it edit the config entry, although I'm not sure what would be required to do this.

Once set via HASS, the `miner.pwd` and `miner.username` attributes can be updated.

**Comment by Schnitzel** [comment]
v1.0.1 allows setting of user/pass now
