### ISSUE TITLE
Test support for multiple miners running in parallel

### ISSUE THREAD

**Issue by UpstreamData** [Schnitzel/hass-miner#172]
Seen a few reports of being unable to run miners in parallel and query both of them via HASS, I have a few theories on this:

- The hostnames being used as a unique ID could be causing the entities to overwrite each other, as (for example) stock antminers all use `Antminer` as their hostname.
- `MinerCoordinator` could be causing issues with multiple miners.  I'm not sure how `MinerCoordinator` is actually handled on the backend of HASS, but if only 1 instance is created and it's expected to handle all miners for the whole `hass-miner` integration, overwriting `coordinator.miner` would cause issues.

Based on these, MAC address could be used as a UUID, or if the issue is related to the miner coordinator, there are ways to coordinate all the miners as a list inside that class.

**Comment by Schnitzel** [comment]
v1.0.0 uses MACs as UniqueIDs now
