### ISSUE TITLE
Issue with install of beta version and a few entitys

### ISSUE THREAD

**Issue by tueftler0** [Schnitzel/hass-miner#189]
Hi there.

I would like to use your HACS addon for my S19J Pro+ miner.
After reinstall your addon, i can switch on/off and show some data.
But "Power Limit" selector, "Miner Consumption" value and "Power limit" calue is not working.

Furthermore if i open HACS and press "reinstall", i dont get the possibility to install the latest beta version.
And the display dont get any information which version are installed at the moment.

Hope you can help to fix that, so i can use the miners more intelligent with NodeRed.

Thank you in advance!
Bjoern

![hacs_addon](https://github.com/Schnitzel/hass-miner/assets/35748555/9227db10-c59a-4f2e-aacc-f3dd671a0fe0)

[home-assistant_miner_2023-07-19T18-51-46.756Z.log](https://github.com/Schnitzel/hass-miner/files/12099472/home-assistant_miner_2023-07-19T18-51-46.756Z.log)

![HAgui](https://github.com/Schnitzel/hass-miner/assets/35748555/0fef973d-90b6-4f62-8a67-3230e44d7a3a)

**Comment by UpstreamData** [comment]
Take a look at this video, see if it helps you?

https://jumpshare.com/v/E1LD5km2XCKlBmga4pjD

**Comment by Domek688** [comment]
When trying to integrate the following error : "Settings cannot be loaded: 500 Internal Server Error Server got itself in trouble"

**Comment by Schnitzel** [comment]
I think this has been addressed in `v1.0.1`. @oscarrdg can you verify that upgrading solved this issue?

**Comment by Domek688** [comment]
> I think this has been addressed in `v1.0.1`. @Domek688 can you verify that upgrading solved this issue?

Hello, 
Yes, the installation is now successful. Thank you.
