### ISSUE TITLE
GitHub returned HttpStatusCode.NOT_FOUND

### ISSUE THREAD

**Issue by Blockvolt** [Schnitzel/hass-miner#193]
Hi,

i can`t add the custom repository with "https://github.com/UpstreamData/hass-miner". Error: "NOT_FOUND"

With "https://github.com/Schnitzel/hass-miner" the download in HACS is loading and doesn`t finish.

**Comment by UpstreamData** [comment]
My fork of this repo is no longer supported, I have removed it in favor of this one.

Please install the beta release, as it has improvements from my fork and more.  This video shows how to do it.

https://jumpshare.com/v/E1LD5km2XCKlBmga4pjD

**Comment by Schnitzel** [comment]
also we have now a stable version out, please try with v1.0.1
