### ISSUE TITLE
can't add miner

### ISSUE THREAD

**Issue by pixelcatcher** [Schnitzel/hass-miner#214]
here is the log:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/miner/__init__.py:24 
Integration: Miner (documentation, issues) 
First occurred: 14:00:46 (6 occurrences) 
Last logged: 15:09:38

Error setting up entry miner-f6383f for miner
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miner/__init__.py", line 24, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by schwoi** [comment]
I am also receiving the same error.

Running BraiinsOS+ Version: 2022-06-20-0-288861e4-22.05-plus
Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

**Comment by schwoi** [comment]
@pixelcatcher just and FYI, I have been able to add miners using the v1.0.0-beta1

**Comment by pixelcatcher** [comment]
correct, I can also add it and switch it on and off with the latest version. however I cant control the power limit. there is just one entity for the device which is the switch.

**Comment by schwoi** [comment]
Yeah you were right, I didn't test that until after.

Another workaround until it is sorted it to use the upstream data repo. This is working for me, to add and control power.
https://github.com/UpstreamData/hass-miner

**Comment by tashgitt** [comment]
Home Assistant and HACS are up to date as of today. I have S19 Pro with original FW (not Braiins).
I tried both both repos (Schnitzel and UpstreamData) and get this on both of them:

`Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 4:02:08 PM (1 occurrences)
Last logged: 4:02:08 PM

Error setting up entry 2x50 for miner
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miner/__init__.py", line 24, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

This error originated from a custom integration.

Logger: root
Source: custom_components/miner/config_flow.py:81
Integration: Miner (documentation, issues)
First occurred: 4:01:59 PM (4 occurrences)
Last logged: 4:02:08 PM

Failed to get hostname for miner: BMMinerX19: 192.168.2.50
192.168.2.50: API Command Error: Invalid command`

Is there anything I can do to make this work? Would I be able to change the mode from Normal to Low Power?

**Comment by epper202** [comment]
> Home Assistant and HACS are up to date as of today. I have S19 Pro with original FW (not Braiins). I tried both both repos (Schnitzel and UpstreamData) and get this on both of them:
> 
> `Logger: homeassistant.config_entries Source: config_entries.py:402 First occurred: 4:02:08 PM (1 occurrences) Last logged: 4:02:08 PM
> 
> Error setting up entry 2x50 for miner Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/miner/**init**.py", line 24, in async_setup_entry hass.config_entries.async_setup_platforms(entry, PLATFORMS) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
> 
> This error originated from a custom integration.
> 
> Logger: root Source: custom_components/miner/config_flow.py:81 Integration: Miner (documentation, issues) First occurred: 4:01:59 PM (4 occurrences) Last logged: 4:02:08 PM
> 
> Failed to get hostname for miner: BMMinerX19: 192.168.2.50 192.168.2.50: API Command Error: Invalid command`
> 
> Is there anything I can do to make this work? Would I be able to change the mode from Normal to Low Power?

Experiencing the same over here.

**Comment by Schnitzel** [comment]
This has been addressed in `v1.0.1`. @pixelcatcher @epper202 @tashgitt  can you verify that upgrading solved this issue?

**Comment by schwoi** [comment]
@Schnitzel can confirm v1.0.1 seems to be working for me.

**Comment by tashgitt** [comment]
That fixed it for me. S19 Braiins OS+ Version: 2023-11-02-0-fd0c1e56-23.10-plus

**Comment by tashgitt** [comment]
That's a little off-topic - once a device has been added, can you check what its IP address is?

**Comment by Schnitzel** [comment]
created https://github.com/Schnitzel/hass-miner/issues/247 so we can track that there
