### ISSUE TITLE
Cannot add integration after upgrade to Home Assitant 23.11

### ISSUE THREAD

**Issue by ethmik** [Schnitzel/hass-miner#241]
2023-11-02 09:18:33.643 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package pyasic==0.36.9: ERROR: Cannot install pyasic==0.36.9 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2023-11-02 09:18:48.945 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package pyasic==0.36.9: ERROR: Cannot install pyasic==0.36.9 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2023-11-02 09:19:03.581 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package pyasic==0.36.9: ERROR: Cannot install pyasic==0.36.9 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2023-11-02 09:19:03.585 ERROR (MainThread) [aiohttp.server] Error handling request

**Comment by ethmik** [comment]
I forgot to mention I am using version v1.0.0-beta1

**Comment by epper202** [comment]
> I forgot to mention I am using version v1.0.0-beta1

I downgraded core version hass and worked. But this was on 0.6.0. Now I'm on V1.0.0.0 hass miner but still 1 version back on core version

**Comment by Buster2k6** [comment]
It doesn't work anymore with Core 2023.11, every time i want to add a miner, it ends in the error message "Error
The configuration flow could not be loaded: 500 Internal Server Error Server got itself in trouble".
Using an old core version permanently cannot be the solution. Is there any other way to control the miner with HA?

**Comment by epper202** [comment]
> It doesn't work anymore with Core 2023.11, every time i want to add a miner, it ends in the error message "Error
> 
> The configuration flow could not be loaded: 500 Internal Server Error Server got itself in trouble".
> 
> Using an old core version permanently cannot be the solution. Is there any other way to control the miner with HA?
> 
> 

We had the same conclusion in topic:

https://github.com/UpstreamData/pyasic/issues/66

Work in progress 🙂

**Comment by Schnitzel** [comment]
I think  has been addressed in `v1.0.1`. @Buster2k6 and @epper202 can you verify that upgrading solved this issue?

**Comment by epper202** [comment]
@Schnitzel It's working again!
But only 1 of my 2 miners, is that correct? read something about this in one of these issue topics a while ago.
Thanks!

**Comment by Schnitzel** [comment]
@epper202 mhh no the multi miner issue should be solved now as well. 
Can you remove all miners from your HomeAssistant and then try to add them again?

**Comment by Buster2k6** [comment]
@Schnitzel thank you very much for the update, now everything works fine, even the power limit, which unfortunately didn't work for me before. Many thanks again.
