### ISSUE TITLE
Upgrade to v1.0.0.0-beta1

### ISSUE THREAD

**Issue by epper202** [Schnitzel/hass-miner#242]
Hi Schnitzel,
I am unable to re-download the HACS integration and then choose V1.0.0.0-beta1.
The ''show beta versions'' is not there. 
Is there a workaround?

Egbert

**Comment by Domek688** [comment]
Try reselecting multiple times, then the Beta version will appear. I have successfully downloaded the beta to HACS, but the beta cannot be integrated. I get the message "Error
Settings could not be loaded: 500 Internal Server Error Server got itself in trouble" when trying to integrate . I'm doing something wrong, but I have no idea what.

**Comment by epper202** [comment]
I went to a previous core firmware of hass since it worked before and I got the same message with the internal server error blabla. 
The downgrade in core did the trick!
Integrated them and made a back up. Keep you posted on findings

**Comment by epper202** [comment]
![image](https://github.com/Schnitzel/hass-miner/assets/107040729/84329b88-69bb-4002-ae22-5fc3755ba635)
 @Domek688 There is no dropdown menu with show beta version

**Comment by epper202** [comment]
Oh wauw I just completely downloaded the wrong repository, now it works in v1.0.0.0 try downgrading the core 1 version and try again

**Comment by epper202** [comment]
Oh wauw I just completely downloaded the wrong repository, now it works in v1.0.0.0 try downgrading the core 1 version and try again

**Comment by Schnitzel** [comment]
we also have a stable version of 1.0.0 out now! Your HACS should suggest the upgrade right away

**Comment by epper202** [comment]
It works flawless including more than 1 integrated miner. 
Thank you!
