### ISSUE TITLE
Integration is using deprecated methods on an instance of NumberEntity

### ISSUE THREAD

**Issue by oscarrdg** [Schnitzel/hass-miner#243]
# Version of the custom_component

v1.0.0-beta1
On Home Assistant Core 2023.10.5

## Describe the bug

I am getting a log message pointing out that the integration is "overriding deprecated methods on an instance of NumberEntity".

Please, have a look at the following message:

## Debug log

Logger: homeassistant.components.number
Source: components/number/__init__.py:203
Integration: Number (documentation, issues)
First occurred: 2:48:43 PM (1 occurrences)
Last logged: 2:48:43 PM

custom_components.miner.number::MinerPowerLimitNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

```

**Comment by Schnitzel** [comment]
This has been addressed in `v1.0.1`. @oscarrdg can you verify that upgrading solved this issue? If not, please reopen :)
