### ISSUE TITLE
Issue adding second miner

### ISSUE THREAD

**Issue by ors86** [Schnitzel/hass-miner#271]
Added first miner, entities appeared.

Added second miner, success message, but no entities appeared.

Logs:

Platform miner does not generate unique IDs. ID 00:00:00:00:00:00-power_limit already exists - ignoring number.worker1_power_limit
10:27:30 PM – (ERROR) Number
Platform miner does not generate unique IDs. ID 00:00:00:00:00:00-active already exists - ignoring switch.worker1_active
10:27:30 PM – (ERROR) Switch
Platform miner does not generate unique IDs. ID 00:00:00:00:00:00-2-chip_temperature already exists - ignoring sensor.worker1_board_2_chip_temperature
10:27:30 PM – (ERROR) Sensor - message first occurred at 10:27:30 PM and shows up 17 times

**Comment by UpstreamData** [comment]
This is an issue with pyasic, what type of miner is this?  pyasic is having trouble figuring out what the mac address of the miner is, so it may be a miner type that isnt recognized.

**Comment by ors86** [comment]
Its antminer s19 pro hydro both. Can i add mac manually?

**Comment by UpstreamData** [comment]
Not something we've added support for, no.  This isn't a miner ive added to pyasic, so it will be using a BMMiner default base class, which doesnt contain the web endpoints needed to get the MAC address.

@Schnitzel is there any way to manually set device UID?

**Comment by UpstreamData** [comment]
I can add it for testing on my secondary branch if you'd like, I just need the miner type string from the API, and the chip count.

If you want to do this let me know, and I (or you) can open an issue on pyasic and ill get it added.  I can explain how to get that info in that issue, its pretty easy.

**Comment by ors86** [comment]
That would be nice. Let me know how i can give you the information you want.

**Comment by UpstreamData** [comment]
See https://github.com/UpstreamData/pyasic/issues/83

**Comment by UpstreamData** [comment]
I found an issue.  There is no way to get the latest version of pyasic working with home assistant as of right now.  The reason for this is that homeassistant is using httpx==0.25.0, and pyasic relies on a feature added in httpx==0.25.2 for parts of its scanning.  Sadly there's nothing I can do about this until they release an update to homeassistant, there isnt even a beta channel for this.  That being said, they have httpx==0.26.0 in the requirements right now on github, so im assuming they will release an update sometime next month that will fix this issue.  Until then I cant really do anything about it.

**Comment by b-rowan** [comment]
Should be fixed now that httpx is up to date.
