### ISSUE TITLE
Add remote miner

### ISSUE THREAD

**Issue by ors86** [Schnitzel/hass-miner#272]
Tried to add miner via ddns address (miner1.customdomain.com:3456) without success.

It would be good to add miners via remote address and not only from lan.

**Comment by UpstreamData** [comment]
This is not simple to do.  IF you want to do it, what you need to do is route miner port 80 to port 80, 443 to 443, 22 to 22, 4028 to 4028, and 50051 to 50051.  Miners expose very specific services on all those endpoints, and without them pyasic will not be able to identify or query them properly.

Specifically:
4028 -> CGMiner standard RPC API
80 -> Web interface
443 -> Secured web interface
22 -> SSH
50051 -> BOS+ gRPC

**Comment by ors86** [comment]
OK i see. So onother approach, more secure, is to have vpn.

**Comment by UpstreamData** [comment]
Correct.  That's usually what I do, but if you want to have miners show up at subdomains, you have to expose those ports sadly.

**Comment by UpstreamData** [comment]
The other option is to expose them, then have a firewall that only accepts traffic coming in from some source, say a cloudflare address, which you can make private.

**Comment by ors86** [comment]
That option with cloudflare sounds good. If you can give more information, how to do it, i would be gratefull.

**Comment by UpstreamData** [comment]
I can't for the life of me remember where I saw that, it was something about a home lab server and making secured requests to it, but even if you know the IP of your local connection you can whitelist that.
