### ISSUE TITLE
Display fan RPM

### ISSUE THREAD

**Issue by Sjors** [Schnitzel/hass-miner#275]
It would be nice to display the fan(s) RPM:

<img width="457" alt="Scherm­afbeelding 2023-12-30 om 20 09 06" src="https://github.com/Schnitzel/hass-miner/assets/10217/a1e04552-7d4f-430a-9ac1-7f744b1c4a03">

This correlates with noise, so an automation could lower the power target (when I'm home) so that the fans consistently run lower.

**Comment by UpstreamData** [comment]
This should be no issue, it's already part of the miner data, so just a matter of getting it put in as an entity.  I'll add this on my branch to be merged in the new year, but it will have to wait until HASS core is updated to work with https 0.26.0.

**Comment by UpstreamData** [comment]
With Home Assistant v2024.1.0 they have updated to `httpx==0.26.0`, so my forkshould work now.  I just added fan speeds there (albeit completely untested), so if you'd like to test them (prior to merging) you can remove the custom repo in HACS, and re-add from [my fork](https://github.com/UpstreamData/hass-miner).

**Comment by Sjors** [comment]
@UpstreamData I'm waiting for the dust to settle on #280, but will try this after.

**Comment by Sjors** [comment]
Oh I see your master branch covers that as well. So I might switch over to your fork.

**Comment by UpstreamData** [comment]
Yep. My fork requires the latest version to home assistant though, so just make sure you're updated or it won't be able to run.

**Comment by Sjors** [comment]
Managed to update and I'm seeing the fan speed, nice!

**Comment by UpstreamData** [comment]
This is now merged in 1.1.0-beta.

**Comment by Sjors** [comment]
Nice! Tested that it still works with the beta release.
