### ISSUE TITLE
More than 3 hashboards? - S19 Hydro 158th - Data only for 3 boards but i have 4

### ISSUE THREAD

**Issue by Rasmusbangp** [Schnitzel/hass-miner#276]
I recently installed the integration, and seems to be very fine, but apparently i only get data from 3 out of my 4 hash boards (Board #0, #1 And #2) 

Is this a fault? Is there anything i can do ?

**Comment by UpstreamData** [comment]
There's nothing that can be done about this right now, pyasic does have support for the hydro (see https://github.com/UpstreamData/pyasic/issues/83), but it won't work until home assistant is updated in the new year to work with httpx 0.26.0.  If you watch this PR, once it is merged it will add support for the hydro, https://github.com/Schnitzel/hass-miner/pull/252.

**Comment by b-rowan** [comment]
Should work in most recent version (v1.1.0).

**Comment by 928driver** [comment]
Hello all :)
I have been using a S19 air cooled which I am controlling with BOS and HASS-Miner and it is workin perfect for me for many months now :)

I recently bought an S19 Pro+ Hyd that have 4 hashboards which I only a few days ago were able to install BOS as I was waiting for support in the latest firmware for my PSU. I can add the miner in HA with HASS-Miner, but I can only see 3 hash boards. Also, I am unable to change the power limit in HA, only switch the miner on/off and monitor values. 

@Rasmusbangp did you get data from all 4 hash boards for your miner?

@b-rowan the issue that I have not being able to change power limit, can it be related to lack of support for my hydro miner and 4 hash boards?

**Comment by b-rowan** [comment]
You're running BOS+ on your hydro?  I will have to check if I have that supported, I think I might need to put out a new version possibly.  I may also need you to get the model name from the `devdetails` command, but I'll reply later if I need that.

**Comment by 928driver** [comment]
@b-rowan yes, I am running BOS+ on my hydro, the last firmware. Right now I do not have access to HA and the miner, but I will collect the data as soon as possible.

**Comment by b-rowan** [comment]
Any luck with `v1.1.2`?

**Comment by 928driver** [comment]
@b-rowan , the 4th hash board is not visible in HA for me with the Antminer Pro+ hyd miner. But it is probably related to the lack of support for my type of miner in pyasic. Pyasic is now having a new revision which probably contain support for my miner, Hass-Miner probably need to be revised to fetch the last pyasic revision right?

**Comment by 928driver** [comment]
@b-rowan , when do you expect the next revision of hass-miner will be released so support for the Antminer Pro+ hyd miner will be added?

**Comment by b-rowan** [comment]
Try `v1.1.13`

**Comment by 928driver** [comment]
@b-rowan , sorry for not replying earlier. My miner has been on repairs, expecting to receive it back shortly from repairs. Also, I see that others are having issues with latest version of Hass miner and HA, so I will wait with updating until those issues are sorted :)
Thanks again for the great work you are doing!

**Comment by 928driver** [comment]
@b-rowan , I have now received my miner back from repairs and with the latest updates of HASS-Miner, it added all hashboards in HA, thank you!
