### ISSUE TITLE
S19 Devices are being Duplicated.

### ISSUE THREAD

**Issue by schwoi** [Schnitzel/hass-miner#287]
## Version of the custom_component

Miner
V1.1.0-beta2

HA
Core 2024.1.1
Supervisor 2023.12.0
Operating System 11.3
Frontend 20240104.0

## Describe the bug

When adding a new device at some point it adds a second device for the same unit. It only seems to happen on the s19 it doesn't seem to do it for the S9. I will test with a T17+ when I get a chance.
![image](https://github.com/Schnitzel/hass-miner/assets/7381086/933cca66-53cc-468d-844b-271e071b6a40)

One device has all of the enties as expected however the second only has a small subset that doesn't get populated.
![image](https://github.com/Schnitzel/hass-miner/assets/7381086/4b8f8fe7-f711-4705-98f4-96ad32c515d3)
![image](https://github.com/Schnitzel/hass-miner/assets/7381086/0f44e853-2b03-4b97-acfd-ca9f1870a516)

## log

```text

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:610
Integration: Sensor (documentation, issues)
First occurred: 10 January 2024 at 09:59:29 (81328 occurrences)
Last logged: 16:38:01

Platform miner does not generate unique IDs. ID f0:58:04:32:2e:a7-2-board_hashrate already exists - ignoring sensor.s19_01_board_2_board_hashrate
Platform miner does not generate unique IDs. ID f0:58:04:32:2e:a7-0-fan_speed already exists - ignoring sensor.s19_01_fan_0_fan_speed
Platform miner does not generate unique IDs. ID f0:58:04:32:2e:a7-1-fan_speed already exists - ignoring sensor.s19_01_fan_1_fan_speed
Platform miner does not generate unique IDs. ID f0:58:04:32:2e:a7-2-fan_speed already exists - ignoring sensor.s19_01_fan_2_fan_speed
Platform miner does not generate unique IDs. ID f0:58:04:32:2e:a7-3-fan_speed already exists - ignoring sensor.s19_01_fan_3_fan_speed

```

**Comment by b-rowan** [comment]
I wonder if it could be creating IDs for `None-n-xyz_metric`?  Possible there's a parsing error there.  Are you able to check the IDs for those unpopulated entities?

**Comment by schwoi** [comment]
Hey @b-rowan ,
Sorry for the delay in getting this to you.

sensor.s19_01_board_0_board_hashrate_2
sensor.s19_01_board_0_board_temperature_2
sensor.s19_01_board_0_chip_temperature_2

Interestingly, when I added another miner it changed the device name to the last added device but the underlying entity id's are stlil the same as above.
![image](https://github.com/Schnitzel/hass-miner/assets/7381086/44948c29-cbf8-4a1c-a441-ab74afa7d39a)

![image](https://github.com/Schnitzel/hass-miner/assets/7381086/aca1e6b2-14e6-4468-9b5d-8ec79a04c6d2)

**Comment by b-rowan** [comment]
I gave this an attempted fix in v1.1.0, can you test it out?

**Comment by schwoi** [comment]
Seems good so far. I removed everything and started fresh. I will monitor it over the next couple of days.

**Comment by schwoi** [comment]
This issue hasn't happened again. Thanks @b-rowan for everything.
