### ISSUE TITLE
Controlls Panel is not in the device 

### ISSUE THREAD

**Issue by Moonraker-007** [Schnitzel/hass-miner#300]
Hello again,

just one more , i hope little problem 

the sensors Efficiency, Miner Consumption and Powerlimit are unknown.
I do not have that Controlls Panel  
I also unable to install Braiin OS+ it does not find my device (IP is checked)

I do have accsess over my Browser with the IP and the miner is working fine 

My Miner

Miner Type	Antminer S9
Hostname	antMiner
Model	GNU/Linux
Hardware Version	30.0.1.3
Kernel Version	Linux 3.14.0-xilinx-ga36f3af-dirty #90 SMP PREEMPT Thu Jun 20 15:01:47 CST 2019
File System Version	Tue Jul 30 20:37:39 CST 2019
Logic Version	V1.3.56
BMminer Version	2.0.0
Uptime	21
Load Average	0.02, 0.12, 0.12

Many thanks again

Carsten

**Comment by b-rowan** [comment]
Stock S9s don't report any power related values, in fact there are no power data points for any stock antminers.  You have to use some kind of aftermarket firmware to be able to access those, and even those firmwares are just guessing.  My guess as to whats happening is that youre using the new toolbox (braiins-toolbox), which doesnt work properly with S9s.  Please try the old toolbox (https://feeds.braiins-os.com/toolbox/latest/), and make sure your miner is on the latest version of stock firmware, then you should be able to install it.

**Comment by Moonraker-007** [comment]
thanks for the toolbox tip !!
I think i don´t change to aftermarket firmware, i will switch on and of via shellyswitch. For powersetting i will see.
best wishes!!
Carsten
