### ISSUE TITLE
Miner setup not possible

### ISSUE THREAD

**Issue by eduros** [Schnitzel/hass-miner#306]
## Version of the custom_component

I am using the newest version v1.1.1.

## Configuration

My Miner is connected via a Mango Router. So the configuration is: S9 Miner -eth- Mango Router -wifi- FritzBox.

## Describe the bug

Hello, 

I tried to setup my S9 Antminer with Stock Firmware on it and it failed. Some days ago I had Braiins OS on it and that worked.

When I enter the IP adress of the miner I get an empty window only showing:

Miner [question mark symbol] [x]
[send button]

## Debug log

```text

2024-01-30 20:29:16.922 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration miner which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

```

**Comment by b-rowan** [comment]
Interesting that this isn't working, but keep in mind you wont have power usage information or autotuning with stock firmware.

**Comment by Chris-S44** [comment]
@b-rowan is it possible that after upgrading to 1.1.2 that it caused my T17's to start tuning again?
They were running fine for months on the same power profiles now they tuning for hours. All I did was upgrade home assistant and hass-miner today.

**Comment by b-rowan** [comment]
Off topic for this issue, please open a new issue next time, but it's possible.  You should downgrade to braiinsOS+ 23.01 if you're using 1.1.2, as I changed some pyasic settings to make that the version it expects now.

**Comment by Chris-S44** [comment]
> Off topic for this issue, please open a new issue next time, but it's possible. You should downgrade to braiinsOS+ 23.01 if you're using 1.1.2, as I changed some pyasic settings to make that the version it expects now.

Sorry I know it's off issue but the previous x17 issue was closed. I wanted to ask before opening a new issue.
I have not upgraded braiins. I'm still on 23.01
Basically I would like to know if upgrading to miner 1.1.2 could have somehow deleted my braiins tuned profiles that are on my miner Sd card?
