### ISSUE TITLE
can't set up these 2 miners together

### ISSUE THREAD

**Issue by bagemihldotpro** [Schnitzel/hass-miner#329]
## Version of the custom_component

v1.1.4rc2

## Describe the bug

Can't add this miners at the same time:

S19 hyd 158
S19 pro hyd 198

More info:
   Doesn't matter in which order I try to add these.
   Both of these miners doesn't ask for user:password config when setting up.

From logs, it seems like the component tries to set up the same sensor names.

another s19 pro hyd 184 gives no issue here, but for this one it's asking for user:password on the set up.

## Debug log

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:636
Integration: Sensor (documentation, issues)
First occurred: 13:21:23 (187 occurrences)
Last logged: 17:34:23

Platform miner does not generate unique IDs. ID None-2-board_temperature already exists - ignoring sensor.s19prohyd198t_board_2_board_temperature
Platform miner does not generate unique IDs. ID None-2-chip_temperature already exists - ignoring sensor.s19prohyd198t_board_2_chip_temperature
Platform miner does not generate unique IDs. ID None-2-board_hashrate already exists - ignoring sensor.s19prohyd198t_board_2_board_hashrate
Platform miner does not generate unique IDs. ID None-0-fan_speed already exists - ignoring sensor.s19prohyd198t_fan_0_fan_speed
Platform miner does not generate unique IDs. ID None-1-fan_speed already exists - ignoring sensor.s19prohyd198t_fan_1_fan_speed

**Comment by b-rowan** [comment]
What firmware do you have on them?  They aren't having a type identified and set, so it's likely they are unsupported by pyasic.

**Comment by b-rowan** [comment]
Yeah, pyasic is using a default type for the miners of `AntminerModern`, which will enable all the functionality, but there are some things tracked in the background such as chip counts and fan counts, so if the miner is not explicitly declared then the model will come back as `None`, which is why this is happening.

I will get it added here, those types look correct.

**Comment by b-rowan** [comment]
Do you happen to have a chip count per board on those?  Looks like neither of them are supported.

You can also just send the result of going to `http://ip/cgi-bin/stats.cgi`.

**Comment by bagemihldotpro** [comment]
Thanks! 

Here what the miner returns:

{"STATUS": {"STATUS": "S", "when": 1709489274, "Msg": "stats", "api_version": "1.0.0"}, "INFO": {"miner_version": "49.0.1.3", "CompileTime": "Sat Dec 17 09:35:13 CST 2022", "type": "Antminer S19 Hydro"}, "STATS": [{"elapsed": 81688, "rate_5s": 138406.51, "rate_30m": 139189.31, "rate_avg": 138604.35, "rate_ideal": 142542.0, "rate_unit": "GH/s", "chain_num": 4, "fan_num": 4, "fan": [0, 0, 0, 0], "hwp_total": 0.047, "miner-mode": 3, "freq-level": 100, "chain": [{"index": 0, "freq_avg": 550, "rate_ideal": 35635.0, "rate_real": 35866.07, "asic_num": 104, "asic": " oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo", "temp_pic": [42, 47, 0, 0, 0, 0], "temp_pcb": [51, 53, 52, 58, 57, 56], "temp_chip": [62, 66, 66, 67, 66, 68], "hw": 271, "eeprom_loaded": true, "sn": "FXDZYN5BBJAAB07YJ", "hwp": 0.0538}, {"index": 1, "freq_avg": 550, "rate_ideal": 35635.0, "rate_real": 34084.86, "asic_num": 104, "asic": " oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo", "temp_pic": [42, 47, 0, 0, 0, 0], "temp_pcb": [49, 53, 53, 56, 57, 55], "temp_chip": [60, 65, 61, 66, 69, 65], "hw": 170, "eeprom_loaded": true, "sn": "FXDZYN5BBJAAB07XX", "hwp": 0.0338}, {"index": 2, "freq_avg": 550, "rate_ideal": 35635.0, "rate_real": 33820.98, "asic_num": 104, "asic": " oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo", "temp_pic": [41, 48, 0, 0, 0, 0], "temp_pcb": [49, 52, 52, 57, 55, 53], "temp_chip": [61, 65, 65, 67, 68, 67], "hw": 250, "eeprom_loaded": true, "sn": "FXDZYN5BBJAAB07Y2", "hwp": 0.0498}, {"index": 3, "freq_avg": 550, "rate_ideal": 35635.0, "rate_real": 34634.62, "asic_num": 104, "asic": " oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo", "temp_pic": [42, 48, 0, 0, 0, 0], "temp_pcb": [51, 52, 55, 58, 58, 55], "temp_chip": [59, 62, 68, 67, 70, 67], "hw": 256, "eeprom_loaded": true, "sn": "FXDZYN5BBJAAB07YC", "hwp": 0.0509}]}]}

**Comment by b-rowan** [comment]
Awesome.  Can you send the same thing for the Pro Hydro please?

**Comment by bagemihldotpro** [comment]
Yep, here we go:


{"STATUS": {"STATUS": "S", "when": 1709489345, "Msg": "stats", "api_version": "1.0.0"}, "INFO": {"miner_version": "49.0.1.3", "CompileTime": "Wed Mar 8 15:30:32 CST 20233", "type": "Antminer S19 Pro+ Hyd."}, "STATS": [{"elapsed": 83976, "rate_5s": 194789.48, "rate_30m": 194222.93, "rate_avg": 194189.75, "rate_ideal": 191000.0, "rate_unit": "GH/s", "chain_num": 4, "fan_num": 4, "fan": [0, 0, 0, 0], "hwp_total": 0.5046, "miner-mode": 0, "freq-level": 100, "chain": [{"index": 0, "freq_avg": 525, "rate_ideal": 48573.0, "rate_real": 47366.96, "asic_num": 180, "asic": " ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo", "temp_pic": [63, 42, 50, 0], "temp_pcb": [63, 42, 50, 57], "temp_chip": [63, 42, 50, 66], "hw": 4358, "eeprom_loaded": true, "sn": "PIEMYPBBCJAAG1GVZ", "hwp": 0.601}, {"index": 1, "freq_avg": 525, "rate_ideal": 48573.0, "rate_real": 48642.39, "asic_num": 180, "asic": " ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo", "temp_pic": [64, 42, 50, 0], "temp_pcb": [64, 42, 50, 57], "temp_chip": [64, 42, 50, 64], "hw": 4020, "eeprom_loaded": true, "sn": "PIEMYPBBCJAAG1GRR", "hwp": 0.5543}, {"index": 2, "freq_avg": 525, "rate_ideal": 48573.0, "rate_real": 49170.16, "asic_num": 180, "asic": " ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo", "temp_pic": [63, 42, 50, 0], "temp_pcb": [63, 42, 50, 57], "temp_chip": [63, 42, 50, 67], "hw": 3916, "eeprom_loaded": true, "sn": "PIEMYPBBCJAAG1GWG", "hwp": 0.5404}, {"index": 3, "freq_avg": 525, "rate_ideal": 48573.0, "rate_real": 49609.96, "asic_num": 180, "asic": " ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo ooo", "temp_pic": [65, 42, 51, 0], "temp_pcb": [65, 42, 51, 59], "temp_chip": [65, 42, 51, 66], "hw": 2337, "eeprom_loaded": true, "sn": "PIEMYPBBCJAAG1GWK", "hwp": 0.3225}]}]}

**Comment by b-rowan** [comment]
Cool.  Give me 15 minutes to get a new pyasic version out, then ill release a version here.

**Comment by b-rowan** [comment]
Should work on 1.1.4rc4.

**Comment by bagemihldotpro** [comment]
Yes, now it's working. Thanks!

Is there a way to spend you a coffee?

**Comment by b-rowan** [comment]
Glad to hear it.

Don't worry about that, just happy to get a few more miners into pyasic!
