### ISSUE TITLE
Broken after HA Core upgrade to 2024.3.0 with miner v1.1.4rc4

### ISSUE THREAD

**Issue by SomeJ0192** [Schnitzel/hass-miner#331]
The miner module is unable to load after upgrading to HA core 2024.3.0.
Miner version v1.1.4rc4

Tried redownloading and installing miner multiple times along with many full restarts of HA with no luck.

Error log entry:

Logger: homeassistant.setup
Source: setup.py:266
First occurred: 8:30:36 PM (1 occurrences)
Last logged: 8:30:36 PM

Setup failed for custom integration 'miner': Requirements for miner not found: ['pyasic==0.54.2'].

**Comment by b-rowan** [comment]
Let me check out the home assistant release, it's possible they updated httpx or something and that's breaking the pyasic install.

**Comment by b-rowan** [comment]
Can you try v1.1.4rc5?  I changed the httpx dependency to be much less strict, so it should work now.

**Comment by SomeJ0192** [comment]
Looks like that fixed it!  The module is loading again and no more errors in the logs.
Thanks man!!
