### ISSUE TITLE
It is impossible to add more than 1 miner

### ISSUE THREAD

**Issue by iRobot39** [Schnitzel/hass-miner#344]
Good afternoon! I encountered a problem, I can only add 1 miner, adding 2-3-4 miners is possible but they are not active. There is also no power control button for the miner. Am I doing something wrong? Antminer T19 S19 firmware Vnish 1.21
![Uploading IMG_4782.jpeg…]()

**Comment by b-rowan** [comment]
That image isn't loading, but no power control was a bug with pyasic, I fixed that with 1.1.4 if you update to the latest.

Regarding the adding multiple miners issue, I'm not really sure how HASS handles device IDs, but sometimes it just decides to be weird, try removing your miners, updating the integration, then re-adding them.

**Comment by iRobot39** [comment]
Thanks for your reply. the new version did add a Manera switch, but the problem with adding more than one Miner remained. Vnish firmware lacks SSH access :(.
The problem looks like this: I calmly add the first Miner by IP address, receive all the information in full from it, when adding Miner number two I only receive information from two coolers, when adding Miner number three or four and so on I do not receive no information about the lane. As soon as I remove Miner number one from the profile, Miner number two immediately receives all the information, number three receives information about the coolers. I can't figure out what the reason is. I can record and send a video.

**Comment by b-rowan** [comment]
Logs would be helpful if you can get them please.  It's likely the logs say something like this: "Platform 'miner' does not generate unique IDs", so it may be an issue with how the IDs are generated, it's likely grabbing "None" some some important piece of the ID and that's what's causing it.

**Comment by iRobot39** [comment]
https://drive.google.com/file/d/1OeYA4Hsekp-_T_K1Giqg8QhQB87EnxP1/view?usp=drivesdk

Sorry to distract you with my problem, but I really liked your integration!
I think a lot of people thank you! I recorded a video so you can see the
problem for yourself!



Сб, 23 марта 2024 г. в 16:08, Brett Rowan ***@***.***>:

**Comment by Nickfost** [comment]
I'm experiencing similar issues, 

unsure if its vnish, pyasic, ha , or hass-miner 

I'm unable to get more than one vnish machine working per installation of ha

**Comment by iRobot39** [comment]
oh yes my friend! this problem does not disappear even on string firmware, I have already tried everything and abandoned this idea. :(

**Comment by b-rowan** [comment]
I've been so busy recently I haven't had a chance to look at it.  @Nickfost we should link up for a c all and ill see if I can fix this.

**Comment by b-rowan** [comment]
Pushed a f ix to pyasic with the latest version 1.1.5 that should fix this?  It wasnt getting the MAC address.

**Comment by Nickfost** [comment]
@iRobot39 yo @b-rowan just fixed this i have 3 miners with vnish with 20 entities each like expected

**Comment by iRobot39** [comment]
You don’t have version 1.1.5, you only have 1.1.6 rc4, and the error is not
fixed in it :(



Пн, 8 апр. 2024 г. в 01:54, Brett Rowan ***@***.***>:

**Comment by iRobot39** [comment]
You don’t have version 1.1.5, you only have 1.1.6 rc4, and the error is not
fixed in it :(


Пн, 8 апр. 2024 г. в 00:30, Nick Foster ***@***.***>:

**Comment by iRobot39** [comment]
Perfect!!🤩 You just made my day! You need to correct the instructions a
little for people like me 🤦‍♂️, the mistake was that for each new miner
you need to create a new integration, and not register it into an existing
one…. 🙈


Пн, 8 апр. 2024 г. в 15:41, Brett Rowan ***@***.***>:
