### ISSUE TITLE
Shows a different hash resul

### ISSUE THREAD

**Issue by iRobot39** [Schnitzel/hass-miner#352]
Good afternoon. Tell me why it shows a different hash result, in the manner of more in the interface, less in the integration interface?
![IMG_5004](https://github.com/Schnitzel/hass-miner/assets/50949371/6a086a1f-b2a0-4e35-98e6-2bd38e05659b)
![IMG_5005](https://github.com/Schnitzel/hass-miner/assets/50949371/e1fc9bde-4e3c-43a3-a46b-db5ccb649d1b)

**Comment by b-rowan** [comment]
They are using different average values.  HASS-miner/pyasic is using the reported hashboard chain rate, and the web interface uses something else.  It's likely that the reported chain rate is a bit behind what the web interface displays, although I'm not sure why.

**Comment by iRobot39** [comment]
can this be fixed?

Ср, 10 апр. 2024 г. в 15:45, Brett Rowan ***@***.***>:

**Comment by b-rowan** [comment]
I'm not sure it can be easily.  Technically pyasic has a fallback hashrate it keeps track of, but that's not useful in this case, since the board hashrate is reporting properly.  It might need to be fixed on the firmware side, but even that might not fix the issue fully.  I can ask the devs about it.

**Comment by iRobot39** [comment]
Ok, thanks.

Ср, 10 апр. 2024 г. в 16:35, Brett Rowan ***@***.***>:

**Comment by b-rowan** [comment]
Seems like it was just grabbing the wrong average, what is in home assistant should actually be more accurate than the dashboard when it comes to shorter periods of time, so it should be good.

**Comment by iRobot39** [comment]
Good evening, my ASICs have been working without interruption for 5 days, but the hashrate is very different from the real indicators. Can I do something myself to get the real hashrate values in HAS?Don’t worry be happy ….10 апр. 2024 г., в 19:14, Brett Rowan ***@***.***> написал(а):﻿
Closed #352 as completed.

**Comment by iRobot39** [comment]
Good evening, my ASICs have been working without interruption for 5 days, but the hashrate is very different from the real indicators. Can I do something myself to get the real hashrate values in HAS?Don’t worry be happy ….10 апр. 2024 г., в 19:14, Brett Rowan ***@***.***> написал(а):﻿
Seems like it was just grabbing the wrong average, what is in home assistant should actually be more accurate than the dashboard when it comes to shorter periods of time, so it should be good.
