### ISSUE TITLE
Changing Power limit causing reset of other settings

### ISSUE THREAD

**Issue by TheMoose92** [Schnitzel/hass-miner#353]
https://github.com/Schnitzel/hass-miner/assets/129767979/ccdc1584-c0b5-4f0c-9074-ee6cbd7752c3

The issue is as follow: As soon as i change the power limit of my miner (S9) via Home assistant, it "forgets"/resets settings such as immersion mode. Refer to my vid below. 

Attached a video with example where you can see `Immersion mode` gets deselected after changing power limit.

**Comment by UpstreamData** [comment]
Can you try with 1.1.7?

**Comment by TheMoose92** [comment]
Works except for 1 important setting: temperature control turns off after changing
![Uploading IMG_7639.png…]()
