### ISSUE TITLE
HACS hass-miner links of Repo are not correct

### ISSUE THREAD

**Issue by tueftler0** [Schnitzel/hass-miner#358]
On my HomeAssistand HACS, the integration of "hass-miner" looks be strange in the webfrontend.
Maybe the issue is coming from a changed repo name/path from "Schnitzel/miner" to "Schnitzel/hass-miner".
I have reinstalled all parts including deletion of the repo path in HACS with some reboots, but the links behind the repo would not be changed.
Also i have searched for the string "Schnitzel/miner" in a full backup of Home Assistant without any success.

![image](https://github.com/Schnitzel/hass-miner/assets/35748555/8ed19657-b941-40f3-9d1f-28142c938c88)

Maybe you can send me a hint where i can change the path to the correct one.

Thank you.

**Comment by b-rowan** [comment]
Oh, that's not a problem haha, it's just a visual issue.  That's the readme for the repo, and the issue is the links for the badges hasn't been updated.  I'll try to make a quick fix for this.

**Comment by b-rowan** [comment]
Should be fixed in v1.1.10rc1 along with some other issues.

**Comment by tueftler0** [comment]
Hey, thats was quite fast - thank you :)
Issue fixed with v1.1.10rc1 !
