### ISSUE TITLE
all sensor disabled

### ISSUE THREAD

**Issue by philspain72** [Schnitzel/hass-miner#366]
The entities are not working anymore on Antminer S9.
Any ideas?
They just stopped working so i reinstalled now the device is showing no entities

-->

## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by tashgitt** [comment]
What is your Home Assistant Core version? I updated from 2023.11.0 to 2024.7.4 and miner integration stopped working. I assume that is the problem for you as well.

**Comment by philspain72** [comment]
I'm using the beta latest but it stopped working on 2024.7 sometime

**Comment by b-rowan** [comment]
Make sure the integration is on the latest version.  HASS core and pyasic both rely on `httpx`, so if the version they use isn't compatible the integration wont load.
