### ISSUE TITLE
Integration doesn't load after 2024.7.4 core update

### ISSUE THREAD

**Issue by tashgitt** [Schnitzel/hass-miner#367]
I updated from 2023.11.0 to 2024.7.4 and miner integration stopped working. How do I fix this? 

SETUP/SYSTEM/LOG:

Logger: homeassistant.setup
Source: setup.py:271
First occurred: 10:13:24 PM (1 occurrences)
Last logged: 10:13:24 PM

Setup failed for custom integration 'miner': Requirements for miner not found: ['pyasic==0.40.3'].

**Comment by b-rowan** [comment]
You may need to update the integration, the most recent version is using `pyasic==0.58.1`.

**Comment by tashgitt** [comment]
I did all the updating (core, has, miner addon) and still the devices used before the updates didn't work. If I add a new device (same IP as the old one) it will work, but I lose all history and automations for the old one (different entity IDs). I ended up installing HA from scratch and added everything fresh. It waisted a lot of hours of my time, but now everything works as expected.
