### ISSUE TITLE
Can't add WhatsMiner M30S+_VH65

### ISSUE THREAD

**Issue by izb2000** [Schnitzel/hass-miner#373]
## Version of the custom_component

[v.1.1.14](https://github.com/Schnitzel/hass-miner/releases/tag/v.1.1.14)

## Describe the bug

Unknown error occurred

How do I support this device?

**Comment by b-rowan** [comment]
Not sure why this wouldn't be working, it is supported - 

https://github.com/UpstreamData/pyasic/blob/af920c4ddae212208a2f494c2cf418b9eff722bd/pyasic/miners/factory.py#L183C1-L183C42

**Comment by izb2000** [comment]
![image](https://github.com/user-attachments/assets/bf9c1551-c816-478b-9623-e90c62e46927)
System
Model	WhatsMiner M30S+_VH65
Hardware Info	M30S+_VH65.H616-CB6V10.P221B-VE2-196802M
Firmware Version	20231225.17.REL
Kernel Version	#1573 SMP PREEMPT Mon Dec 25 17:57:57 CST 2023
Miner Version	4.9.2-git-5e499e3

**Comment by b-rowan** [comment]
Can you try with v1.1.15rc3?

**Comment by izb2000** [comment]
![image](https://github.com/user-attachments/assets/6c6b73e0-864b-4999-bdba-9597670a8b67)

**Comment by iRobot39** [comment]
I'm trying to add Whatsminer m20s m21s, I get an error message. I add by IP, and by MAC address p, the situation does not change, an error message :(
![IMG_6917](https://github.com/user-attachments/assets/7450b3d3-b80b-4df7-94bf-60411239d618)
![Uploading IMG_6921.png…]()

**Comment by b-rowan** [comment]
Can you try with v1.1.17?  Lots of updates, so hopefully this fix was one of them.

**Comment by izb2000** [comment]
> Can you try with v1.1.17? Lots of updates, so hopefully this fix was one of them.

![image](https://github.com/user-attachments/assets/55f608f4-1364-4078-b3a6-b200ba55fb2b)

**Comment by izb2000** [comment]
v1.1.18 is working!
