### ISSUE TITLE
Integration does not work S19j Pro

### ISSUE THREAD

**Issue by Denny0815** [Schnitzel/hass-miner#388]
I have 2 S19j Pro (100TH), in version 1.1.4 I was able to integrate both and now with version 1.1.9 - 1.1.15 this is no longer possible.
I enter everything and I only get one integrated, the other one I can enter everything, but it does not come to the point where I can select the room and it is then displayed:
Setup failed, will try again: Check logs.

LOGS:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.miner.coordinator
Quelle: custom_components/miner/coordinator.py:84
Integration: Miner (Dokumentation, Probleme)
Erstmals aufgetreten: 17:04:33 (7 Vorkommnisse)
Zuletzt protokolliert: 17:12:38

Failed to call hashboards on S19j Pro (BOS+): 192.168.0.75 while getting data.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyasic/miners/base.py", line 496, in _get_data
    miner_data[data_name] = await function(**args_to_send)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyasic/miners/backends/braiins_os.py", line 934, in _get_hashboards
    hashboards[idx].temp = board["boardTemp"]["degreeC"]
    ~~~~~~~~~~^^^^^
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/miner/coordinator.py", line 84, in _async_update_data
    miner_data = await self.miner.get_data(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyasic/miners/base.py", line 535, in get_data
    gathered_data = await self._get_data(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyasic/miners/base.py", line 498, in _get_data
    raise APIError(
pyasic.errors.APIError: Failed to call hashboards on S19j Pro (BOS+): 192.168.0.75 while getting data.

**Comment by b-rowan** [comment]
Seems like the length of the hashboards getting instantiated initially is too short for some reason.  Strange that one would work, but not both, they should be doing the same thing in the background...

**Comment by Denny0815** [comment]
The miner that does not work is a hashboard connected to the 4th data socket because the 2nd one no longer works

**Comment by b-rowan** [comment]
Ahhhh, yes.  That would cause it.  I'll see if I can figure out a solution to that, but the way I'm doing it right now makes that tricky.

**Comment by Denny0815** [comment]
OK, I'm curious and will wait and see

**Comment by Denny0815** [comment]
I have now cooled down the immersion and plugged the cable back into the second socket and the miner is recognized immediately, but unfortunately I have problems with the socket, can you perhaps include the fourth socket in the next update?

**Comment by b-rowan** [comment]
> can you perhaps include the fourth socket in the next update?

I have to look into this, it's not quite as simple as it may seem, because of the way the antminers report their hashboards.  Even on BOS+ things are a bit weird.

**Comment by Denny0815** [comment]
Yes, if not I'll have to have a look, I'll get a new board and then it's good.

**Comment by b-rowan** [comment]
Try out v1.1.16rc1 (pre-release version).  I tried a fix in pyasic.

**Comment by Denny0815** [comment]
Ok, but I can only test it tomorrow, I'll let you know then.
Thanks for the great support

**Comment by ThorPrez** [comment]
I´ve tried out v1.1.16rc1 (pre-release version) and still not working with S19j Pro !

**Comment by b-rowan** [comment]
> I´ve tried out v1.1.16rc1 (pre-release version) and still not working with S19j Pro !

The specific issue here is that the hashboards are outside of standard sequence, you are likely having a different issue.  If you can, please open a new issue with logs and the version of your miners firmware.

**Comment by ThorPrez** [comment]
Hi.
Two S19j Pro with different boards, Beaglebone and CVtek.
Both running with Braiins.

**Comment by b-rowan** [comment]
Can you give this a shot with 1.1.17?  It fixed the install issue, and if your miners are on latest it should hopefully just work...
