### ISSUE TITLE
Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Bennygithub85** [Schnitzel/hass-miner#406]
by adding miner integration

## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by b-rowan** [comment]
Please actually fill out the form, if you provided logs I could actually look into this if it's not what I think it is...

In any case, AFAIU this is the same issue as #393, please read https://github.com/Schnitzel/hass-miner/issues/393#issuecomment-2438171292
