### ISSUE TITLE
[Feature Request]: Support for S19J Pro (BBB)

### ISSUE THREAD

**Issue by BertisAU** [Schnitzel/hass-miner#60]
I have recently installed the Braiins OS+ firmware on my BBB S19J Pros.

I have tried to add your awesome integration, hoping it would already support my ASICs but it is not able to locate them or provide any data when I enter the IP.

Do you plan to support this firmware in the future? 

Thanks!

**Comment by thetimechain** [comment]
Hi, I was wondering about the exact same thing. It works so well with my S9, I purchased an S19 recently and expected to be able to control it the same way. I was wondering if there was any update on this. Currently running  2023-01-22-0-d0ed01e3-23.01-plus

**Comment by UpstreamData** [comment]
We are currently working on getting this worked in, just patching up PR #39 for merge, then that miner type should be supported.

**Comment by Schnitzel** [comment]
v1.0.1 has now support for S19s
